// Increment 1 refactor-boundary proof.
//
// fixtures/midwife-v1-prerefactor.json was generated by the PRE-refactor
// evaluate() (single-pass boolean evaluator) for every midwife test profile
// with a pinned clock. The refactored evaluate() (shared core + mode-aware
// condition evaluation) must reproduce those outputs byte-for-byte.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { evaluate } from "@shared/career-evaluator/v1/evaluate";
import type { CareerDecisionPackV1 } from "@shared/career-evaluator/v1/types";

const __dirname_local = dirname(fileURLToPath(import.meta.url));
const midwife = JSON.parse(readFileSync(resolve(__dirname_local, "../../../content/career-packs/midwife/1.0.0.json"), "utf-8")) as CareerDecisionPackV1;
const fixture = JSON.parse(readFileSync(resolve(__dirname_local, "fixtures/midwife-v1-prerefactor.json"), "utf-8")) as Record<string, unknown>;

const NOW = "2026-07-12T12:00:00.000Z";

describe("V1 refactor parity (midwife, all 12 profiles)", () => {
  it("covers every profile in the fixture", () => {
    expect(Object.keys(fixture).sort()).toEqual(midwife.testProfiles.map((p) => p.id).sort());
  });

  for (const profileId of Object.keys(fixture)) {
    it(`profile ${profileId} produces an identical V1 result across the refactor boundary`, () => {
      const profile = midwife.testProfiles.find((p) => p.id === profileId)!;
      const result = evaluate(midwife, profile.answers, { now: NOW });
      expect(result).toEqual(fixture[profileId]);
    });
  }
});
